import { mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

import { expect, type Locator, type Page } from '@playwright/test';

interface EvidenceCheckpoint {
  step: number;
  stem: string;
  title: string;
  persona: string;
  ready?: Locator;
}

interface EvidenceRow extends Omit<EvidenceCheckpoint, 'ready'> {
  file: string;
  path: string;
}

const LIFECYCLE_STEPS = [
  'Admin creates and configures the CFP',
  'Speakers submit proposals',
  'Committee reviews proposals',
  'Admin accepts and rejects proposals',
  'Speakers are notified and complete confirmation details',
  'Admin starts creating the schedule',
  'Committee and speakers are notified',
  'Speakers and committee review the working schedule',
  'CFP closes',
  'Admin makes the schedule public',
  'Admin decides to add last-minute speakers',
  'Speakers submit late proposals',
  'Committee reviews late proposals',
  'Admin accepts and rejects late proposals',
  'Late speakers are notified and complete confirmation details',
  'Admin updates the public schedule',
  'Event is done and the workspace is archived',
] as const;

/**
 * Full-page lifecycle evidence is deliberately opt-in. The normal test suite
 * does no extra navigation, filesystem work, or screenshot rendering.
 */
export class EvidenceRecorder {
  readonly enabled: boolean;

  private readonly directory: string;
  private readonly rows: EvidenceRow[] = [];
  private readonly stems = new Set<string>();

  constructor(directory = process.env.QA_EVIDENCE_DIR?.trim()) {
    this.enabled = Boolean(directory);
    this.directory = directory ? resolve(directory) : '';
  }

  async prepare(page: Page): Promise<void> {
    if (!this.enabled) return;
    await mkdir(this.directory, { recursive: true });
    await page.setViewportSize({ width: 1440, height: 1000 });
    await this.writeIndex();
  }

  async capture(page: Page, checkpoint: EvidenceCheckpoint): Promise<void> {
    if (!this.enabled) return;
    if (checkpoint.step < 1 || checkpoint.step > 17) {
      throw new Error(`Evidence step ${checkpoint.step} is outside the 17-step lifecycle.`);
    }
    if (this.stems.has(checkpoint.stem)) {
      throw new Error(`Duplicate evidence checkpoint: ${checkpoint.stem}`);
    }

    await expect(page.locator('#main-content')).toBeVisible();
    if (checkpoint.ready) await expect(checkpoint.ready).toBeVisible();
    await page.evaluate(async () => {
      await document.fonts.ready;
      await new Promise<void>((done) => {
        requestAnimationFrame(() => requestAnimationFrame(() => done()));
      });
    });

    const file = `${checkpoint.stem}.png`;
    await page.screenshot({
      path: resolve(this.directory, file),
      fullPage: true,
      animations: 'disabled',
      caret: 'hide',
    });

    this.stems.add(checkpoint.stem);
    this.rows.push({
      step: checkpoint.step,
      stem: checkpoint.stem,
      title: checkpoint.title,
      persona: checkpoint.persona,
      file,
      path: new URL(page.url()).pathname,
    });
    await this.writeIndex();
  }

  private async writeIndex(): Promise<void> {
    const covered = new Set(this.rows.map((row) => row.step));
    const personas = [...new Set(this.rows.map((row) => row.persona))];
    const lines = [
      '# Exact 17-step CFP lifecycle — UI evidence',
      '',
      'Generated by `tests/e2e/criticalPath.spec.ts` with `QA_EVIDENCE_DIR` set.',
      'Each image is a full-page capture taken only after its named accessible UI state was visible.',
      '',
      `- Lifecycle coverage: ${covered.size}/17 steps`,
      `- Personas captured: ${personas.length ? personas.join(', ') : 'none yet'}`,
      '- Viewport: 1440 × 1000 (full page)',
      '',
      '| Step | Lifecycle stage | Evidence checkpoint | Persona | Route |',
      '| ---: | --- | --- | --- | --- |',
      ...LIFECYCLE_STEPS.map((stage, index) => {
        const step = index + 1;
        const matches = this.rows.filter((row) => row.step === step);
        if (matches.length === 0) return `| ${step} | ${stage} | Pending | — | — |`;
        return `| ${step} | ${stage} | ${matches
          .map((row) => `[${row.title}](./${row.file})`)
          .join('<br>')} | ${[...new Set(matches.map((row) => row.persona))].join('<br>')} | ${[
          ...new Set(matches.map((row) => `\`${row.path}\``)),
        ].join('<br>')} |`;
      }),
      '',
    ];
    await writeFile(resolve(this.directory, 'index.md'), lines.join('\n'), 'utf8');
  }
}
